### ISSUE TITLE
Fastboot Support

### ISSUE THREAD

**Issue by ronco** [ronco/ember-cli-meta-tags#12]
Current implementation will not pre-render the meta tags within [ember-cli-fastboot](https://github.com/tildeio/ember-cli-fastboot).

Dependent on resolution to https://github.com/tildeio/ember-cli-fastboot/pull/49 and/or https://github.com/krisselden/simple-dom/pull/12.

**Comment by rondale-sc** [comment]
@ronco Both of these issues seem to have been merged.  Is this addon now fastboot compatible?

**Comment by rondale-sc** [comment]
Was looking at #29 and plugged it into my app.  Started blowing up on this line: https://github.com/ronco/ember-cli-meta-tags/pull/29/files#diff-ea7ed9533b757165c39f249f4d3f7d5bL22.  If I can help on this issue in anyway let me know.  :beers:

Also, awesome addon.  Thanks for all the good work.

**Comment by ronco** [comment]
Hey @rondale-sc,

Yeah I ran into that issue with `Ember.$` as well.  I actually fixed that up last week (forgot to commit) and ran into [this](https://github.com/tildeio/htmlbars/pull/455).  Once that's merged into htmlbars/ember I think we'll be set.  I'll ping the rest of the FastBoot team tomorrow on that PR and see if we can get it moving.

Thanks!
-Ron

**Comment by mschinis** [comment]
Hey all, is there any progress or estimate on this?

**Comment by ronco** [comment]
@mschinis Yes!  It is working with fastboot + ember canary now.  I will cut a 2.0.0 release this afternoon.  Thanks for the nudge 😄

**Comment by ronco** [comment]
@mschinis I just published 2.0.0 to npm.  Let me know if you see any issues.
