### ISSUE TITLE
Multiple tags produced on nested routes.

### ISSUE THREAD

**Issue by benmurden** [ronco/ember-cli-meta-tags#19]
Let's say I have a route that looks like `/collection/book/chapter`, and each route level had its own, different, meta tags. Currently, when visiting a chapter, all the meta tags for the chapter, book, and collection will be rendered, meaning that services like Facebook will only pick up the latter, because it appears farthest down the DOM.

We'd like to replace the meta tags when traversing down through the nested routes, so is there a way of doing that?

**Comment by ronco** [comment]
Hey Ben,

Thanks for reporting this. Currently there is not a way to do that.

However I'm really glad you brought this up now. I'm in the process of
rewriting the implementation to be backed by a service and I wasn't certain
if anyone was nesting tags.

I'll make sure to preserve that feature (and fix these collisions). I think
the natural behavior would be to have the nested most tags take precedent
(chapter in your example). Does that work for you?

Updating this library is a nights & weekend gig for me, but I'll try to
have a beta you can test in the next day or so.

-Ron

**Comment by benmurden** [comment]
@ronco 

Fantastic, thanks for your quick response. Services do seem to be the way to do this sort of thing, now.

You'd be correct, the rightmost (deepest) route should take precedence, as it would in a regular webpage. If we need to bubble up to higher level details for any reason we can easily use a combination of conditionals and model relation traversing.

I'm happy to help debug when you have a beta version.

**Comment by ronco** [comment]
Great!

I'll cc you on the PR when I open it.

**Comment by ehubbell** [comment]
Can anyone comment on the status of this issue? Would love to take advantage of this feature.

**Comment by ronco** [comment]
Hey Eric,

I stalled out on updating documentation for this. I'm going to put it
together tonight. Sorry for the delay!

-Ron

**Comment by ehubbell** [comment]
No sweat Ron! Thanks for the update and I’ll look for the update. Appreciate your efforts :)

Eric



On Oct 20, 2015, at 5:36 PM, ronco <notifications@github.com> wrote:

Hey Eric,

I stalled out on updating documentation for this. I'm going to put it
together tonight. Sorry for the delay!

-Ron
