### ISSUE TITLE
Duplicate meta tags

### ISSUE THREAD

**Issue by pedrokost** [ronco/ember-cli-meta-tags#21]
If I have a meta-description tag in the index.html, and try to replace it with a specific one using this addon, it will not replace the existing meta tag, but just add a new one below.

**Comment by ronco** [comment]
Hey Pedro,

I can't think of a way to accomplish what you're looking for with the
current release. However the next release has the ability to override
parent tags in child routes.

With this you would include the base meta-description tag in your
application route and then other routes that provide that same tag would
replace it.

The currently open PR #20 has this feature if you want to give it a try. I
still need to add unit tests and documentation before I release I on npm
(later this week I expect).

Let me know if that approach works for you.

Thanks!

**Comment by pedrokost** [comment]
Hi @ronco,

I will be looking forward to the next release. For now, I have removed the meta-description from the `index.html` and have added it using your addon to all the *child* routes. This is good enough for awhile, the only worry I have it how removing the meta-description from the `index.html` will affect SEO on search engines which don't execute Javascript.

Cheers

**Comment by ronco** [comment]
Hey Pedro,

For search engines and Facebook you should definitely take a look at
prerender.io or ember-prerender. That will make sure you get the benefit of
this library for all bots and nested routes.

If those aren't an option I can imagine a solution where this library
provides a content-for block that builds in default tags created with a
config. And then at run time it treats those configured base tags tags as a
parent of even the application route. That could solve providing initial
tags if you can't prerender server side.

I think you're best of going prerendered if you can.

-Ron

**Comment by wilgoszpl** [comment]
@ronco, is there any update about when this feature could be officially available?

**Comment by ronco** [comment]
Hey @wilgoszpl

Sorry the PR stalled out on documentation. The tests are done on that PR now. I'll work on the documentation updates tonight.

**Comment by wilgoszpl** [comment]
Thanks, I need this feature very much to implement in my project.
