### ISSUE TITLE
OG & Twitter not reading our meta tags

### ISSUE THREAD

**Issue by ehubbell** [ronco/ember-cli-meta-tags#24]
Hi There,

I've implemented the updated library for nesting dynamic meta tag data however it appears that neither OpenGraph nor Twitter are reading our new meta tags. 

When I look at our <head> file I see all the meta tags I've just created listed at the bottom of our <head> file. When I visit the OG Debugger & Twitter Validator - neither receive any of the content from our meta tags. When I hardcoded that information in our `index.html` file before - they both did. 

At first, I thought this was because the new meta tags were being inserted as part of {{content-for 'head-footer'}} and that needed to be moved up above our stylesheets. When I moved that snippet of code up however nothing changed. The meta tags are still being inserted at the bottom of our <head> after our stylesheets. 

I'm not sure whether that's the issue or not but, either way, OG nor Twitter are recognizing that these tags exist though they clearly do in our <head> file. Any ideas on a fix for this? All the meta tags are populating correctly (including nested routes) which is great. Please see below for a snippet from our <head> file or visit http://myhubapp.com and inspect the elements. 

````
<meta id="ember612" content="Myhub | Social Planning" name="title" class="ember-view">
<meta id="ember614" content="Welcome to Myhub - the fastest, easiest way to plan group activities and pool money with your friends. Get started today with no added transaction fees." name="description" class="ember-view">
<meta id="ember616" content="Myhub | Social Planning" name="og:title" class="ember-view">
<meta id="ember618" content="Welcome to Myhub - the fastest, easiest way to plan group activities and pool money with your friends. Get started today with no added transaction fees." name="og:description" class="ember-view">
<meta id="ember620" content="Myhub" name="og:site_name" class="ember-view">
<meta id="ember622" content="en_US" name="og:site_locale" class="ember-view">
<meta id="ember624" content="website" name="og:type" class="ember-view">
<meta id="ember626" content="https://d257h11pznfsji.cloudfront.net/assets/images/misc/myhub-cover-8324fda3f5576b68240be61721fbb382.png" name="og:image" class="ember-view">
<meta id="ember628" content="http://myhubapp.com" name="og:url" class="ember-view">
<meta id="ember630" content="summary_large_image" name="twitter:card" class="ember-view">
<meta id="ember632" content="http://myhubapp.com" name="twitter:site" class="ember-view">
<meta id="ember634" content="@myhubapp" name="twitter:creator" class="ember-view">
<meta id="ember636" content="Myhub | Social Planning" name="twitter:title" class="ember-view">
<meta id="ember638" content="Welcome to Myhub - the fastest, easiest way to plan group activities and pool money with your friends. Get started today with no added transaction fees." name="twitter:description" class="ember-view">
<meta id="ember640" content="https://d257h11pznfsji.cloudfront.net/assets/images/misc/myhub-cover-8324fda3f5576b68240be61721fbb382.png" name="twitter:image" class="ember-view">
````

Thanks for your help!
Eric

**Comment by ronco** [comment]
Hey Eric,

I'm sorry to hear you're having trouble.

Do you have some sort of application server (express.js, rails etc.) serving your index.html?  Most crawlers (Google being the only exception I'm aware of) do not execute javascript.  So Facebook and Twitter won't see any page content that is generated by js and thus Ember and this library.

You can simulate accessing your page as Facebook with curl on the command line:
`curl -A "facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)" https://www.myhubapp.com/`.  You'll see none of your page content is rendered, just the script include links in the body:
```html
  <body data-spy='scroll' data-target='.scrollspy'>

    <script src="https://d257h11pznfsji.cloudfront.net/assets/vendor-c05b998b6e7d507c68ff4fc0b9daa2d2.js"></script>
    <script src="https://d257h11pznfsji.cloudfront.net/assets/myhub-web-39debbc4f2a26be92433e5e313a8cdaf.js"></script>

  </body>
```

You can take a look at the discussion on #16 for more context.

You'll need to ensure you run a web server and then integrate a pre-rendering solution to run your app server side for the crawler requests.  Eventually [ember-cli-fastboot](https://github.com/tildeio/ember-cli-fastboot) and [fastboot-server](https://github.com/ember-fastboot/ember-fastboot-server) will be ember core team provided solutions.  Once they're ready for production use I will be making this library compatible (#12).  They are not quite ready for prime time though.

In the time being I recommend you checkout [prerender.io](https://prerender.io).  That service has support for many different server technologies, and as a bonus is a local Front Range company.

Let me know if that is your problem.  I'm happy to continue helping trouble shoot.

-Ron

**Comment by ehubbell** [comment]
Hey Ron,

I see. We’re working on incorporating Prerender.io <http://prerender.io/> but are running into issues there now. Will report back when that’s finished.

Thanks for the help!
- Eric

On Oct 27, 2015, at 9:34 AM, ronco <notifications@github.com> wrote:

Hey Eric,

I'm sorry to hear you're having trouble.

Do you have some sort of application server (express.js, rails etc.) serving your index.html? Most crawlers (Google being the only exception I'm aware of) do not execute javascript. So Facebook and Twitter won't see any page content that is generated by js and thus Ember and this library.

You can simulate accessing your page as Facebook with curl on the command line:
curl -A "facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)" https://www.myhubapp.com/. You'll see none of your page content is rendered, just the script include links in the body:

  <body data-spy='scroll' data-target='.scrollspy'>

    <script src="https://d257h11pznfsji.cloudfront.net/assets/vendor-c05b998b6e7d507c68ff4fc0b9daa2d2.js"></script>
    <script src="https://d257h11pznfsji.cloudfront.net/assets/myhub-web-39debbc4f2a26be92433e5e313a8cdaf.js"></script>

  </body>
You can take a look at the discussion on #16 <https://github.com/ronco/ember-cli-meta-tags/issues/16> for more context.

You'll need to ensure you run a web server and then integrate a pre-rendering solution to run your app server side for the crawler requests. Eventually ember-cli-fastboot <https://github.com/tildeio/ember-cli-fastboot> and fastboot-server <https://github.com/ember-fastboot/ember-fastboot-server> will be ember core team provided solutions. Once they're ready for production use I will be making this library compatible (#12 <https://github.com/ronco/ember-cli-meta-tags/issues/12>). They are not quite ready for prime time though.

In the time being I recommend you checkout prerender.io <https://prerender.io/>. That service has support for many different server technologies, and as a bonus is a local Front Range company.

Let me know if that is your problem. I'm happy to continue helping trouble shoot.

-Ron

**Comment by ronco** [comment]
Hey Eric,

How's the prerender.io integration coming along?

-Ron

**Comment by ehubbell** [comment]
Hi Ron,

Thanks for the follow up. Yeah, I've taken a look at Prerender.io going so far as to install the middleware on our rails server and follow the installation / testing directions on their website. When I test our website using Prerender.io's methods, I see the correct HTML in our source file without any Javascript. I can also log into my Prerender.io account, click 'Preview Raw HTML', and see the correct HTML tags in there too. 

That said, it doesn't appear that the crawlers are getting through our site. Prerender.io only shows the pages that I've entered in there manually and when I run the command you gave me above, I get nothing.

Do I need to generate a sitemap.xml and then upload that to Prerender.io in order for them to cache all our pages and serve them to crawlers? And, any ideas on why we're able to see the correct data using prerender's test environment but not in production?

Thx!
Eric

**Comment by ronco** [comment]
Hey Eric,

I don't have any direct experience with the rails middleware, I've only used the node.js middleware.  

@thoop do you have any ideas on what may be causing @ehubbell issues?

Thanks,

Ron

**Comment by ehubbell** [comment]
Ron,

We got this figured out. The issue was on our end. We were trying to serve the HTML using Prerender from our Rails server. Turns out, our Ember app is served by a separate Node.js server. Communication issue on our end. The library is now working great. Thanks for your help.

Best,
Eric




On Nov 12, 2015, at 9:49 AM, ronco <notifications@github.com> wrote:

Hey Eric,

I don't have any direct experience with the rails middleware, I've only used the node.js middleware.

@thoop <https://github.com/thoop> do you have any ideas on what may be causing @ehubbell <https://github.com/ehubbell> issues?

Thanks,

Ron

**Comment by ronco** [comment]
Hey Eric,

Thanks for the update!  I'm glad to hear you got it all worked out.

Cheers,

Ron
