### ISSUE TITLE
facebook crawler not reading meta tags

### ISSUE THREAD

**Issue by mlchai** [ronco/ember-cli-meta-tags#30]
I think I might be missing something. The package itself works just fine, but it seems to not process in a way that facebook's crawler sees the tags. Is there a way to get this package to insert the tags so that crawlers can see them?

**Comment by ronco** [comment]
Hi @mlchai,

Facebook's crawler doesn't execute JavaScript. So this package alone (which executes purely within the js Ember app) can't produce those tags for Facebook. You'll need to prerender your app server side and serve a static html page for Facebook to understand your tags. This can be done with a service such as prerender.io and soon ember-cli-fastboot. 

You can take a look at #16 and #24 for more context. I'm also happy to answer any questions.

**Comment by mlchai** [comment]
Thanks for links, those seem promising. Gonna close this for now but will reopen if anything comes up.
