### ISSUE TITLE
Recommended way of adding valid tags

### ISSUE THREAD

**Issue by vsymguysung** [ronco/ember-cli-meta-tags#33]
I am trying not to hard-coded `VALID_HEAD_TAGS` to support `noscript` tag.
Any recommended way of doing this ? Thanks in advance.

**Comment by ronco** [comment]
Hey @vsymguysung,

This is a great point.  I think the addon should support `noscript` out of the box.  Would you like to submit a PR for this?  Otherwise I can add it this weekend.

Thanks!

**Comment by vsymguysung** [comment]
@ronco I will do that. Thanks again for the addon ! 👍

**Comment by ronco** [comment]
@vsymguysung published as v2.0.1.  Thanks!
