### ISSUE TITLE
Unable to create link tags with Fastboot

### ISSUE THREAD

**Issue by claire-lee** [ronco/ember-cli-meta-tags#37]
Not sure if this is an issue with the add-on or with my setup - I'm currently trying to generate tags such as `<link href="something" rel="next">` in my Ember app, but these tags don't appear in the DOM on initial load with Fastboot (but do appear when the page loads normally). My code looks something like this:
```
afterModel: function() {
  let headTags = [{
      type: 'link',
      tagId: 'link-pagination-next',
      attrs: {
        rel: 'next',
        href: 'something' // I've also tried using content: 'something' here
      }
    },
    ...
  ];

  this.set('headTags', tags);
}
```
I'm also adding title and meta tags in this method, and those appear in the DOM on initial Fastboot load. Is anyone else able to create link tags with Fastboot?

**Comment by claire-lee** [comment]
Looks like upgrading to Ember 2.7 fixed this issue

**Comment by ronco** [comment]
Hi Claire,


Sorry for the non-response on this initially.  I've been pre-occupied with the day job and moving the past couple weeks.

Glad to here Ember 2.7 fixed it up.  Yes 2.7 is required for full Fastboot compatibility.
