### ISSUE TITLE
Error in Ember 2.8: Component error can't use 'attributeBindings' on a tag-less component

### ISSUE THREAD

**Issue by oscarni** [ronco/ember-cli-meta-tags#40]
In Ember 2.8 this addon prevents the page from rendering and Ember throws error: 

```
Uncaught Error: Assertion Failed: You cannot use `attributeBindings` on a tag-less component: <myapp@component:head-layout::ember203>
```

How can we resolve this?

**Comment by oscarni** [comment]
Never mind, I had another addon adding `attributeBindings` to all components. This addons still works as expected 👍

**Comment by patcoll** [comment]
I am getting this error. I removed the library and usage of `ember-cli-meta-tags` and this error went away.

I did a quick grep and the problem seems to be in `ember-cli-head`, so I'm guessing the problem is there? Can anyone provide any direction?

**Comment by jakeleboeuf** [comment]
@oscarni which addon was that?

**Comment by oscarni** [comment]
`ember-hammertime` added an attribute bindning in its initializer. I believe theyve fixed it though.
