### ISSUE TITLE
Doesn't work on ember-cli 2.8.0?

### ISSUE THREAD

**Issue by milindalvares** [ronco/ember-cli-meta-tags#41]
I was struggling to get it to work with my app, then decided to try on a fresh install of 2.5.1. Worked fine on that. Updated that to stock 2.8.0, and same problem.
![screen shot 2016-09-18 at 1 01 48 am](https://cloud.githubusercontent.com/assets/5129514/18610492/825efd08-7d3b-11e6-8815-03b44961e603.png)

**Comment by milindalvares** [comment]
Looking at Issue #40 it seems to be working for that person. I've pushed a test app repo [here](https://github.com/milindalvares/testapp-ember-meta-tags) in case anyone feels like looking at it.

**Comment by Cerealkillerway** [comment]
For me too it is not working anymore after upgrading to ember 2.8.0 (was working fine on 2.7)

**Comment by linearza** [comment]
Same here - tracing it, it seems the instance initializer isnt fired up, so need to now call the tag collection explicitly via the service everywhere:

```service.get('router').on('didTransition', function() {
    service.collectHeadTags();
  });```

**Comment by ronco** [comment]
Thanks for the investigation @linearza!  I'll see if I can get to the bottom of it tonight.

**Comment by ronco** [comment]
@milindalvares @Cerealkillerway @linearza Please have a look at #42 .  I think this solves the issues with Ember 2.8.  If it works for you I'll merge and cut a new release to npm.

**Comment by ronco** [comment]
Published as 3.0.0 (major semver bump since this definitely drops Ember versions < 2.0).
