### ISSUE TITLE
meta() has no access to the context

### ISSUE THREAD

**Issue by joachimhs** [ronco/ember-cli-meta-tags#5]
When implementing the meta() function, it has no access to the route's properties. In fact, "this" is undefined, so even this.controllerFor('routeName') fails. 

I've "solved" this  by hacking the call the setMeta() inside of the _runSetMeta() function, adding "this" as the only parameter to meta(): 

So, instead of: 

    return this.setMeta(meta());

I am left with: 

    return this.setMeta(meta(this));

This mean that, in my route, I can add this function: 

    meta: function(route) {
      var controller = route.controllerFor('routeName');
      //Rest of code
    }

Am I missing something, or can this change be brought into the ember-cli-meta-tags source?

**Comment by ronco** [comment]
Hi @joachimhs,

Thanks for bringing this to my attention.  The context for the execution of `meta` should definitely be set to the route.  I'll get that fixed this morning and ensure I have a test that would catch this in the future.

Thanks!

**Comment by sunil-shrestha** [comment]
If you want to set metaTags from other properties or set from model itself, one way could be run setMetaTags function afterModel. Here is an example that worked for me.

    export default Ember.Route.extend(RouteMetaMixin,{
     metaTags: {},

     afterModel: function(model) {
  	   this.setMetaTags(model);
     },

     setMetaTags: function (model) {
       var metaTags = {
         'name': {
           'description' : model.get('description'),
           'keywords'    : model.get('name')
          }
       };

       this.set('meta', metaTags);
     }

    }

**Comment by ronco** [comment]
@joachimhs It should be fixed in 0.1.1 which I just published to npm.  Let me know if you run into any issues.  Thanks again!

**Comment by christiannaths** [comment]
@sunil-shrestha Thanks for posting your example. Real, working, and practical examples like that really need to be in the readme!  cc/ @ronco
