### ISSUE TITLE
[Proposal] CP-ify all the things

### ISSUE THREAD

**Issue by bcardarella** [ronco/ember-cli-meta-tags#50]
**Warning** this idea is kind of rough right now and may make more sense in my head than how I am articulating here. In any event, I think the basic concept makes sense and would appreciate thoughts on its merit.

Problem: Currently meta-tags builds the `headTags` object by crawling up the routes. It will collect and build an `Ember.A` object with the values from each route level. This presents what might be considered a 'non-standard' approach to forcing meta tag recalculation.

Solution: We should strive for CPs and being able to bust the cache of a given route's tags. At this point `headTags` should be a nested collection of CPs that can be recalculated at any point. When a route's meta tags are recalculated its children should also be forced to recalculate.

Unknowns: how to properly override a parent route's meta tag if a child route's is preferable. With a nested model that isn't as simple as the current flattened array solution.

In addition to being able to recalculate the tags themselves being able to recalculate the a given tag's properties would be desirable.

**Comment by ronco** [comment]
I think this is a great idea and much more in line with standard Ember practices.  The current tag reset implementation has always been a bit inconvenient.

I'm happy to have a look if you start prototyping this.

@blimmer thoughts?

**Comment by blimmer** [comment]
👍  going with computed properties certainly feels more ember-y and could help reduce computationally heavy re-crawling on every transition.

I could definitely see some unknown issues with the refactor but I'd be happy to have a look some initial prototyping as well.

**Comment by bcardarella** [comment]
I need to carve out a day or two to spike the implementation. Maybe before the New Year.
