### ISSUE TITLE
Ember-cli-meta-tags don't work with ember-page-title

### ISSUE THREAD

**Issue by jpnathan** [ronco/ember-cli-meta-tags#63]
I follow the doc and it works fine without another addon based on ember-cli-head, but after install ember-page-title, the headTags defined on route didn't work. Is there some known issue?

**Comment by snewcomer** [comment]
@jpnathan Thanks for pointing this out.  `5.0` was released a month or so ago.  Does this solve it for you?

**Comment by snewcomer** [comment]
Closing for now.  Thx for the report and feel free to reopen if you notice any more issues!
