### ISSUE TITLE
Not working properly with ember-page-title

### ISSUE THREAD

**Issue by joeygilkie** [ronco/ember-cli-meta-tags#67]
This add-on seems to be incompatible with ember-page-title. Just tested with a simplistic test case where the title tag is rendered twice, with the lower one being the only one to change.

**Comment by begedin** [comment]
@joeygilkie We've released 5.0 yesterday. If you're still using this addon, can you confirm that the update fixes things for you?

**Comment by snewcomer** [comment]
This should be fixed with #71 and the `5.0` release!  Lmk if you have any other issues.  Closing for now.
