### ISSUE TITLE
Ember-cli-meta-tags already integrated on project

### ISSUE THREAD

**Issue by michaeljymsgutierrez** [ronco/ember-cli-meta-tags#90]
Currently I have a project which uses this module `ember-cli-meta-tags`.
Now I'm wondering why the links I sent on social sites doesn't fetch the meta (description, title, image).
Does ember-cli-meta-tags requires the application to be server side rendered to make SEO works?

**Comment by GavinJoyce** [comment]
possibly related to https://github.com/ronco/ember-cli-meta-tags/pull/81#discussion_r496774941
